const fs=require('fs'),path=require('path');
global.window=global;
for(const f of ['math','machineGeometry','kinematics','paperTransform','singularityAnalysis','collisionDetection','structuralEstimate','motorAnalysis','mechanics','validation','bom','bubbleText','patterns','simulation','renderers'])require('../js/'+f+'.js');
const folder=path.resolve(__dirname,'../exports');fs.mkdirSync(folder,{recursive:true});
const sim=new MotioSimulation.Simulation();
fs.writeFileSync(path.join(folder,'MOTIO-V4-5-mechanical.svg'),MotioRenderers.mechanismSVG(sim,true));
fs.writeFileSync(path.join(folder,'MOTIO-V4-5-section.svg'),MotioRenderers.sectionSVG(sim));
fs.writeFileSync(path.join(folder,'MOTIO-V4-5-pen-detail.svg'),MotioRenderers.detailSVG(sim,'pen'));
fs.writeFileSync(path.join(folder,'MOTIO-V4-5-BOM.csv'),MotioBOM.csv(sim.geometry));
console.log('Shared-geometry mechanical, spindle, pen detail and BOM exports generated.');
